name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Testing Repo
      uses: actions/checkout@v4
    - name: Clone FrontEnd Repo
      uses: actions/checkout@v4
      with:
        repository: GunjanBidpath/demo-inventory-frontend
        path: inventorytrack-frontend
    - name: Clone BackEnd Repo
      uses: actions/checkout@v4
      with:
        repository: GunjanBidpath/demo-inventory-backend
        path: inventorytrack-backend
    
    - name: Start Backend
      run: docker compose -f inventorytrack-backend/docker-compose.yml up -d --build || true

    - name: Check Postgres Logs
      run: docker logs $(docker ps -aqf "name=postgres-db")


    - name: Start Frontend
      run: docker compose -f inventorytrack-frontend/docker-compose.yml up -d --build

    - name: Debug API availability
      run: curl -i http://localhost:4000/products
      
    - name: Wait for services to be healthy
      run: |
        sleep 15
        docker ps
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browser
      run: npx playwright install chromium --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    
